source 'https://rubygems.org'

gem 'sfn'
gem 'sparkle-pack-aws-availability-zones'
gem 'sparkle-pack-aws-instance-types',         :git => 'https://github.com/gswallow/sparkle-pack-aws-instance-types.git'
gem 'sparkle-pack-aws-my-load-balancers',      :git => 'https://github.com/gswallow/sparkle-pack-aws-my-load-balancers'
gem 'sparkle-pack-aws-my-s3-buckets',          :git => 'https://github.com/gswallow/sparkle-pack-aws-my-s3-buckets.git'
gem 'sparkle-pack-aws-my-security-groups',     :git => 'https://github.com/gswallow/sparkle-pack-aws-my-security-groups.git'
gem 'sparkle-pack-aws-my-server-certificates', :git => 'https://github.com/gswallow/sparkle-pack-aws-my-server-certificates.git'
gem 'sparkle-pack-aws-my-sns-topics',          :git => 'https://github.com/gswallow/sparkle-pack-aws-my-sns-topics.git'
gem 'sparkle-pack-aws-my-subnets',             :git => 'https://github.com/gswallow/sparkle-pack-aws-my-subnets.git'
gem 'sparkle-pack-aws-my-route53-zones',       :git => 'https://github.com/gswallow/sparkle-pack-aws-my-route53-zones.git'
gem 'sparkle-pack-cfn-init-ansible',           :git => 'https://github.com/gswallow/sparkle-pack-cfn-init-ansible.git'
