- hosts: minion
  connection: local
  vars:
    docker_version: "{{ lookup('env', 'DOCKER_VERSION') }}"
    ecs_agent_version: "{{ lookup('env', 'ECS_AGENT_VERSION') }}"
    enable_streaming_logs: "{{ lookup('env', 'ENABLE_STREAMING_LOGS') }}"
    enable_sumologic: "{{ lookup('env', 'ENABLE_SUMOLOGIC') }}"
    mem2x: "{{ ansible_memtotal_mb * 1024 * 2 }}"
  roles:
    - common
    - swap
    - docker
    - aws_ecs
    - { role: sumologic, when: enable_sumologic == 'true' }
    - newrelic
- hosts: controller
  connection: local
  vars:
    docker_version: "{{ lookup('env', 'DOCKER_VERSION') }}"
    ecs_agent_version: "{{ lookup('env', 'ECS_AGENT_VERSION') }}"
    enable_streaming_logs: "{{ lookup('env', 'ENABLE_STREAMING_LOGS') }}"
    enable_sumologic: "{{ lookup('env', 'ENABLE_SUMOLOGIC') }}"
    mem2x: "{{ ansible_memtotal_mb * 1024 * 2 }}"
  roles:
    - common
    - swap
    - docker
    - aws_ecs
    - newrelic
    - { role: sumologic, when: enable_sumologic == 'true' }
- hosts: empire_ami
  connection: local
  vars:
    docker_version: "{{ lookup('env', 'DOCKER_VERSION') }}"
    ecs_agent_version: "{{ lookup('env', 'ECS_AGENT_VERSION') }}"
    enable_streaming_logs: "{{ lookup('env', 'ENABLE_STREAMING_LOGS') }}"
    enable_sumologic: "{{ lookup('env', 'ENABLE_SUMOLOGIC') }}"
    mem2x: "{{ ansible_memtotal_mb * 1024 * 2 }}"
  roles:
    - {role: build_ami, tags: ['build_ami']}
    - common
    - docker
    - aws_ecs
